// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMI87S7CpWiExi19y6w4V2blf-AxVyBLk',
    appId: '1:106181398821:web:257dbdb97b22764a8acacc',
    messagingSenderId: '106181398821',
    projectId: 'hg-sip',
    authDomain: 'hg-sip.firebaseapp.com',
    storageBucket: 'hg-sip.appspot.com',
    measurementId: 'G-4JW79X8ZCP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjxbjzjwjbGcpSuzXf4lUBAXqIuC0mnZ0',
    appId: '1:106181398821:android:eaa3d3a07c5b27098acacc',
    messagingSenderId: '106181398821',
    projectId: 'hg-sip',
    storageBucket: 'hg-sip.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDKi3VHPzYows9P0JrHISm7R10t5XWg2Lc',
    appId: '1:106181398821:ios:d3dc17745784a7408acacc',
    messagingSenderId: '106181398821',
    projectId: 'hg-sip',
    storageBucket: 'hg-sip.appspot.com',
    iosClientId: '106181398821-r9hvihupns0vpue535odstbrggb2r42p.apps.googleusercontent.com',
    iosBundleId: 'tech.minimal-apps.toghraphy',
  );
}
